### ISSUE TITLE
Call to understand Keycloak operator needs

### ISSUE THREAD

**Issue by Sgitario** [snowdrop/team#681]
Address some of the Keycloak team concerns. Insist on them creating issues for tracking purposes.
Current pain points for them:
- Lack of documentation
- CRD generator issues (fabric8 client)
- Testing support
- Synchronization of dependencies
- Productization support

**Comment by cmoulliard** [comment]
Why have you created this task under label `customer-support` as it do not seem to be related to a customer case ? @metacosm

**Comment by metacosm** [comment]
It's a customer case from the perspective of the Java Operator SDK project.

**Comment by cmoulliard** [comment]
> It's a customer case from the perspective of the Java Operator SDK project.

Not from the point of view about what I should report as `keycloak team` is not a Red Hat customer ;-) Can you switch the label to use `topic/peer-request` ?

**Comment by metacosm** [comment]
They are a customer for which we are being asked to do productization and support, isn't that what a customer is? :)
The only difference is that we're doing it for free. 😄

**Comment by cmoulliard** [comment]
Keycloak is the name of a MW team and not a Red Hat customer which has opened a support case

**Comment by metacosm** [comment]
> Keycloak is the name of a MW team and not a Red Hat customer which has opened a support case

They nevertheless behave like one and we should be treating them as such. When we productize the SDK, we will be bound by the same rules that apply to customers (more or less). That's something that needs to be taken into account and the reason why I created this issue under customer support and not peer request because the implications will more or less be the same as supporting customers. If we're not ready for this, we shouldn't undertake that effort.
Actually, I should create a `risk` ticket for this… 😄

**Comment by cmoulliard** [comment]
> Actually, I should create a `risk` ticket for this… 😄

OR simply rephrase the title's text to `Keycloak team reported some concerns which should be addressed as they ....` WDYT ? @metacosm
