### ISSUE TITLE
Check why variables are missing from the released pom file

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#740]
Related to dekorateio/dekorate#861

**Comment by Sgitario** [comment]
The only way I found to keep using the properties is updating the Flatten plugin with:

From:

```
<dependencyManagement>expand</dependencyManagement>
<properties>remove</properties>
```

To:

```
<dependencyManagement>keep</dependencyManagement>
<properties>keep</properties>
```

The problem is that dependencies within the dependencyManagement section won't be expanded... This means that the transitive dependencies won't be part of the bom (but it should continue working).

The good thing is that the plugin dependencies will keep being expanded which was the original issue: https://github.com/snowdrop/spring-boot-bom/issues/62
